apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jenkins-x-bot/policy-engine-test-22:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jenkins-x-bot/policy-engine-test-22:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: policy-engine-test-22
        chartPath: charts/policy-engine-test-22
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jenkins-x-bot/policy-engine-test-22"
          image.tag: "{{.DIGEST_HEX}}"
